### PR TITLE
Heap stats

### PR DESCRIPTION
**Pull request by leosunmo**
Add a command to print heap stats for nodes in the cluster.

Haven't written tests for this yet. If you want me to I can take a look at that when I have time.

Elasticsearch 1.7:
```
+---------------------------+------+----------+-----------+--------+--------------------+---------------+
|           NAME            | ROLE | HEAP MAX | HEAP USED | HEAP % | NON-HEAP COMMITTED | NON-HEAP USED |
+---------------------------+------+----------+-----------+--------+--------------------+---------------+
| elasticsearch-17-data-0   | d    | 5.3 GB   | 4.3 GB    | 81 %   | 118.9 MB           | 116.2 MB      |
| elasticsearch-17-data-1   | d    | 5.3 GB   | 4.1 GB    | 76 %   | 118.1 MB           | 115.8 MB      |
| elasticsearch-17-data-2   | d    | 5.3 GB   | 3.9 GB    | 73 %   | 118.2 MB           | 115.4 MB      |
| elasticsearch-17-data-3   | d    | 5.3 GB   | 4.3 GB    | 81 %   | 118.7 MB           | 115.6 MB      |
| elasticsearch-17-data-4   | d    | 5.3 GB   | 3.7 GB    | 69 %   | 117.3 MB           | 115.1 MB      |
| elasticsearch-17-master-0 | M    | 5.3 GB   | 217.8 MB  | 4 %    | 64.9 MB            | 63.8 MB       |
| elasticsearch-17-master-1 | M    | 5.3 GB   | 129.8 MB  | 2 %    | 66.1 MB            | 65.1 MB       |
| elasticsearch-17-master-2 | M    | 5.3 GB   | 142.3 MB  | 2 %    | 60.5 MB            | 59.6 MB       |
+---------------------------+------+----------+-----------+--------+--------------------+---------------+
```
Elasticsearch 5, all nodes are masters and data nodes:
```
+--------------------+------+----------+-----------+--------+--------------------+---------------+
|        NAME        | ROLE | HEAP MAX | HEAP USED | HEAP % | NON-HEAP COMMITTED | NON-HEAP USED |
+--------------------+------+----------+-----------+--------+--------------------+---------------+
| elasticsearch-56-0 | Md   | 2.1 GB   | 825.6 MB  | 39 %   | 143.4 MB           | 136.0 MB      |
| elasticsearch-56-1 | Md   | 2.1 GB   | 966.9 MB  | 46 %   | 162.9 MB           | 154.0 MB      |
| elasticsearch-56-2 | Md   | 2.1 GB   | 969.5 MB  | 46 %   | 152.3 MB           | 144.6 MB      |
| elasticsearch-56-3 | Md   | 2.1 GB   | 738.1 MB  | 35 %   | 117.6 MB           | 111.3 MB      |
| elasticsearch-56-4 | Md   | 2.1 GB   | 977.6 MB  | 47 %   | 143.6 MB           | 136.0 MB      |
+--------------------+------+----------+-----------+--------+--------------------+---------------+
```
Elasticsearch 7:
```
+-----------------------------+-------+----------+-----------+--------+--------------------+---------------+
|             NAME            | ROLE  | HEAP MAX | HEAP USED | HEAP % | NON-HEAP COMMITTED | NON-HEAP USED |
+-----------------------------+-------+----------+-----------+--------+--------------------+---------------+
| elasticsearch-7-es-data-0   | itdm  | 8.6 GB   | 648.6 MB  | 7 %    | 200.9 MB           | 168.6 MB      |
| elasticsearch-7-es-data-1   | itdm  | 8.6 GB   | 3.7 GB    | 42 %   | 205.4 MB           | 172.6 MB      |
| elasticsearch-7-es-data-2   | itdm  | 8.6 GB   | 3.0 GB    | 35 %   | 201.8 MB           | 170.2 MB      |
| elasticsearch-7-es-master-0 | Mitdm | 8.6 GB   | 2.1 GB    | 24 %   | 199.3 MB           | 169.3 MB      |
| elasticsearch-7-es-master-1 | Mitdm | 8.6 GB   | 2.8 GB    | 33 %   | 219.0 MB           | 180.9 MB      |
| elasticsearch-7-es-master-2 | Mitdm | 8.6 GB   | 872.0 MB  | 10 %   | 200.5 MB           | 167.4 MB      |
+-----------------------------+-------+----------+-----------+--------+--------------------+---------------+
```

### CODE REVIEW

**Comment by leosunmo** [comment]
Wondering how useful the non-heap stats are. Never seem to see anything above ~200MB on even my busiest clusters. Don't know enough about it to judge, would love some feedback.

**Comment by nickcanz** [comment]
Thanks for this @leosunmo! I plan on looking at this next week sometime.

**Comment by nickcanz** [comment]
@leosunmo can you merge in the latest changes? I've updated versions/dependencies of things so that there won't be this CI failure on an old go version

**Comment by leosunmo** [comment]
All passing now @nickcanz

**Comment by nickcanz** [comment]
Thanks @leosunmo looks great!

**Pull request merged**
